
export const menuList = [
    {
        id:1,
        name:"AI创作平台",
        icon:"edit-2",
        children:[
            {
                name:"写作工具",
                icon:""
            },
            {
                name:"自然语言处理模型",
                icon:""
            },
            {
                name:"写作提示",
                icon:""
            },
            {
                name:"内容检测",
                icon:""
            },
            {
                name:"论文查重",
                icon:""
            },
            {
                name:"文献阅读",
                icon:""
            },
            {
                name:"网络文学",
                icon:""
            },
        ]
    },
    {
        id:2,
        name:"AI互动平台",
        icon:"chart-3d",
        children:[
            {
                name:"聊天机器人",
                icon:""
            },
            {
                name:"知识问答",
                icon:""
            },
            {
                name:"搜索引擎",
                icon:""
            },
            {
                name:"搜图",
                icon:""
            },
            {
                name:"搜书",
                icon:""
            },
        ]
    },
    {
        id:3,
        name:"AI影视平台",
        icon:"play-circle",
        children:[
            {
                name:"视频生成-文生视频",
                icon:""
            },
            {
                name:"视频后期",
                icon:""
            },
            {
                name:"动作捕捉",
                icon:""
            },
            {
                name:"字幕翻译",
                icon:""
            },
            {
                name:"换脸",
                icon:""
            },
            {
                name:"虚拟人物",
                icon:""
            },
            {
                name:"视频模型",
                icon:""
            },
        ]
    },
    {
        id:4,
        name:"AI绘画平台",
        icon:"image",
        children:[
            {
                name:"绘图生成-文生图",
                icon:""
            },
            {
                name:"绘画模型",
                icon:""
            },
            {
                name:"绘画提示",
                icon:""
            },
            {
                name:"绘画社区",
                icon:""
            },
            {
                name:"3D生成",
                icon:""
            },
            {
                name:"图形工作站",
                icon:""
            },
        ]
    },
    {
        id:5,
        name:"AI视觉平台",
        icon:"browse",
        children:[
            {
                name:"视觉设计",
                icon:""
            },
            {
                name:"头像",
                icon:""
            },
            {
                name:"摄影",
                icon:""
            },
            {
                name:"图像处理",
                icon:""
            },
            {
                name:"图像擦除",
                icon:""
            },
            {
                name:"字体设计",
                icon:""
            },
            {
                name:"服装设计",
                icon:""
            },
            {
                name:"空间设计",
                icon:""
            },
            {
                name:"设计素材",
                icon:""
            },
        ]
    },
    {
        id:7,
        name:"AI语音平台",
        icon:"sound-high",
        children:[
            {
                name:"文字转语音",
                icon:""
            },
            {
                name:"语音转文字",
                icon:""
            },
            {
                name:"语音降噪",
                icon:""
            },
            {
                name:"音乐鉴赏",
                icon:""
            },
            {
                name:"音乐制作",
                icon:""
            },
            {
                name:"语音合成",
                icon:""
            },
        ]
    },
    {
        id:8,
        name:"AI企业平台",
        icon:"usergroup",
        children:[
            {
                name:"人力资源",
                icon:""
            },
            {
                name:"法律服务",
                icon:""
            },
            {
                name:"企业服务",
                icon:""
            },
            {
                name:"金融服务",
                icon:""
            },
            {
                name:"企业提效",
                icon:""
            },
            {
                name:"电子合同",
                icon:""
            },
        ]
    },
    {
        id:9,
        name:"AI办公平台",
        icon:"system-code",
        children:[
            {
                name:"翻译",
                icon:""
            },
            {
                name:"制作PPT",
                icon:""
            },
            {
                name:"PPT资源",
                icon:""
            },
            {
                name:"办公工具",
                icon:""
            },
            {
                name:"办公效率",
                icon:""
            },
            {
                name:"思维导图",
                icon:""
            },
            {
                name:"文档处理",
                icon:""
            },
        ]
    },
    {
        id:10,
        name:"AI运营平台",
        icon:"chart-line",
        children:[
            {
                name:"营销工具",
                icon:""
            },
            {
                name:"数据分析",
                icon:""
            },
            {
                name:"产品经理",
                icon:""
            },
            {
                name:"行业报告",
                icon:""
            },
            {
                name:"流量优化",
                icon:""
            },
            {
                name:"舆情分析",
                icon:""
            },
            {
                name:"自媒体",
                icon:""
            },
            {
                name:"资讯门户",
                icon:""
            },
        ]
    },
    {
        id:11,
        name:"AI学习平台",
        icon:"book",
        children:[
            {
                name:"教育助理",
                icon:""
            },
            {
                name:"开发课堂",
                icon:""
            },
        ]
    },
    {
        id:12,
        name:"AI资讯",
        icon:"internet",
        children:[
            {
                name:"每日新闻",
                icon:""
            },
            {
                name:"工具排行榜",
                icon:""
            },
        ]
    },
]

const menuDataList = [

]